excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - CodeChallenge/AppDelegate.swift
disabled_rules:
    - trailing_whitespace
    - empty_parameters
    - identifier_name
