# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeChallenge

    # Pod for HTTPS request
    pod 'Alamofire'

    # Pod for cache and retrieve images
    pod 'Kingfisher'

    # Pod for JSON parsing
    pod 'SwiftyJSON'

end
